### ISSUE TITLE
Instructions "expose api by modifying manifest" not very clear

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services#8]
# Module: 01
#### Step: 00

Description of issue
The instructions at step "Expose a new scope or role through the application manifest" are not very clear. It should describe in the answer key to repeat the same thing for the Hello ASPNET Core Identity 01 app by modifying the Manifest and check the result.

Repro steps:

1. Select App Registrations and select Hello ASPNET Core Identity
2. Select Manifest
3. Find "oauth2Permissions": [] near line 26
4. Add the following code from the Contoso App manifest: "{ ...}
5. Open PowerShell and enter the command: "New-Guid"
6. Copy the generated GUID
7. Return to the Manifest of the Hello ASPNET Core Identity 01 app.
8. Change the value of the id in oath2Permissions with the copied value of the GUID.
9. Press Save
10. Click on **Expose an API" and verify the newly created scopy by modifing the Manifest.

**Comment by b-deen** [comment]
Hello, I'm not sure that I understand the suggestion here.  Can you please elaborate if you still find this to be an issue?  I know this issue was submitted some months ago.
The task titled "Expose a new scope or role through the application manifest" walks through the steps to modify the manifest to add a new scope.  The following task walks through how to configure the client application with the permission for that scope.
